feat(slugrunner):update stack to heroku-18
teamhephy/slugrunner pull request #7
Opened 2018-10-27 16:39 UTC by duanhongyi

All of the following test cases are passed:

https://github.com/deisthree/example-clojure-ring.git
https://github.com/deisthree/example-go.git
https://github.com/deisthree/example-java-jetty.git
https://github.com/duanhongyi/example-multi.git
https://github.com/deisthree/example-nodejs-express.git
https://github.com/deisthree/example-php.git
https://github.com/deisthree/example-play.git
https://github.com/duanhongyi/example-python-django.git
https://github.com/deisthree/example-python-flask.git
https://github.com/deisthree/example-ruby-sinatra.git
https://github.com/deisthree/example-scala.git

2018-10-28 00:30 UTC, Cryptophobia requested changes
Just a minor commit message change here as well before we merge. Can you change the commit message to follow the style: https://docs.teamhephy.com/contributing/submitting-a-pull-request/#commit-style

2018-10-28 02:56 UTC, duanhongyi commented
> Upgrade heroku-images to heroku-18, cooperate with [slugbuilder](https://github.com/teamhephy/slugbuilder/pull/10)

It has been changed, but my English is not very good, I am sorry.

2018-10-30 17:47 UTC, Cryptophobia approved these changes

2018-10-30 17:48 UTC, Cryptophobia commented
Thanks @duanhongyi ! :+1:

2018-10-30 17:48 UTC, merged